# Generated by Django 4.2.6 on 2023-11-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressourcezone',
            name='AccesControle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ressourcezone',
            name='ActionaMener',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ressourcezone',
            name='Archive',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ressourcezone',
            name='Caracteristique',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ressourcezone',
            name='Contrainte',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ressourcezone',
            name='Potentialite',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ressourcezone',
            name='UtilisationActuelle',
            field=models.TextField(),
        ),
    ]
