# Generated by Django 4.2.6 on 2023-12-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_finance_financement_infrastructure_minfrastructure_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Pays',
        ),
        migrations.RenameModel(
            old_name='PotentialiteDesZones',
            new_name='PotentialitesDesZones',
        ),
        migrations.RenameModel(
            old_name='ProgrammeDesMinisteres',
            new_name='ProgrammesDesMinisteres',
        ),
        migrations.AlterField(
            model_name='finance',
            name='Budget',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='finance',
            name='BudgetPrevu',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='finance',
            name='DPrevu',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='finance',
            name='DRealise',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='finance',
            name='FPrevu',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='finance',
            name='FRealise',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='finance',
            name='IDExercice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='finance',
            name='IDZone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='finance',
            name='ID_Finance',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='finance',
            name='IPrevu',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='finance',
            name='IRealise',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='finance',
            name='RPrevu',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='finance',
            name='RRealise',
            field=models.FloatField(),
        ),
    ]
