# Generated by Django 5.0.1 on 2024-01-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_country_pays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financement',
            name='IDTFinance',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='financement',
            name='ID_Finance',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='financement',
            name='ID_Source',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='financement',
            name='MontantPrevu',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='financement',
            name='MontantRealise',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='financement',
            name='Observation',
            field=models.TextField(),
        ),
    ]
