# Generated by Django 5.0.1 on 2024-01-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_financement_idtfinance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='Observation',
            field=models.TextField(),
        ),
    ]
