# Generated by Django 5.0.1 on 2024-01-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_infrastructure_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialitesdeszones',
            name='Potentialites',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='probleme',
            name='Probleme',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='provenancefinance',
            name='Observation',
            field=models.TextField(),
        ),
    ]
