# Generated by Django 4.2.6 on 2023-11-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localite',
            field=models.CharField(max_length=255, null=True, verbose_name='CodeS_Localite'),
            name='CodeS_Localite',
        ),
    ]
