# Generated by Django 4.2.6 on 2023-11-27 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_country_total'),
        ('app', '0003_rename_localite_Code_Localite'),
    ]

    operations = [
    ]
