# Generated by Django 4.2.6 on 2023-11-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_paysageurbain_potentialite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paysageurbain',
            name='Potentialite',
        ),
    ]
